#!/bin/bash
set -ex
repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
rm -rf $repo_dir/bin
$repo_dir/../buildlib/iso dmd-build dmd -i -I=$repo_dir/src -run $repo_dir/make.d test
rm -rf $repo_dir/bin
$repo_dir/../buildlib/iso ldc-build ldmd2 -i -I=$repo_dir/src -run $repo_dir/make.d test
