language: generic
git:
  depth: false
  submodules: false
script:
# install build library
- git clone --depth=1 --branch=master https://github.com/dragon-lang/buildlib.git ../buildlib
# Make sure our iso profiles work
- ../buildlib/iso dmd-build exit
- ../buildlib/iso ldc-build exit
# Run the tests
- ./test/test-with-nix
